### ISSUE TITLE
TODO v0.1.0

### ISSUE THREAD

**Issue by shrektan** [shrektan/ymd#3]
- [ ] more tests for date part functions
- [ ] probably different API for date part functions to avoid name conflicts
- [ ] a vignette on performance
- [ ] parallel?
- [x] better error handling (now on error, it reports rust panicked with the real message being thrown to stderr instead of the r's stderr) - **Not very satisfied the solution, but it's much better now**
- [ ] package size on CRAN's mac build (sometimes it contains a debug file, which is 5MB and looks useless to me)
